route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'

templates:
- '/etc/alertmanager/templates/*.tmpl'

receivers:
- name: 'email'
  email_configs:
  - to: 'gxlcliqi@126.com'
    smarthost: smtp.126.com:25
    from: jacqli@126.com
    auth_username: jacqli@126.com
    auth_password: 
    send_resolved: true