route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'email'
  routes:
    - match:
        frequency: daily
      repeat_interval: 1h  
      receiver: 'webhook'  
    - match:
      repeat_interval: 10m  
      receiver: 'webhook2'  

templates:
- '/etc/alertmanager/templates/*.tmpl'

receivers:
- name: 'email'
  email_configs:
  - to: 'gxlcliqi@126.com'
    smarthost: smtp.126.com:25
    from: jacqli@126.com
    auth_username: jacqli@126.com
    auth_password: 
    send_resolved: false
- name: webhook
  webhook_configs:
  - url: 'http://host.docker.internal:7000/webhook/uat'
    send_resolved: false
- name: webhook2
  webhook_configs:
  - url: 'http://host.docker.internal:7000/webhook/dev'
    send_resolved: false          